---
title: "About"
---

Hi, I'm Greg.

I'm a 4th year PhD student in the [laboratory of Dr. Ilia Karatsoreos](https://www.karatsoreoslab.org/ilia-karatsoreos) at the University of Massachusetts Amherst. 

### My research interests include:
- understanding the effect of circadian desynchronization on the immune response and behavior following exposure to an inflammatory stimulus. You can view our recent publication on this topic [here](http://www.sciencedirect.com/science/article/pii/S0889159120301744).
- determining how the brain protects itself from a viral infection. Our goal is to identify the critical factors that influence the severity of viral infection of the brain.

### My Story
I studied Exercise Physiology as an undergraduate student at Shippensburg University of Pennsylvania. My interest in exercise physiology stemmed from my desire to optimize my athletic performance as a NCAA Division II Track & Field athlete. Following my athletic career, I decided to pursue a M.S. degree in Biology at my undergraduate institution as a stepping-stone into medical school. During this pursuit, I began a Master's thesis with the goal of determining the prevalence of ticks and tickborne pathogens in southwestern Pennsylvania. I also had the opportunity to work at the Naval Medical Research Center in Silver Spring, Maryland during this time. Here, I worked as an intern in the Naval Research Enterprise Internship Program (NREIP) and as a contracted employee for the Henry Jackson Foundation for the Advancement of Military Medicine (HJF). These experiences ignited a newfound passion for research. This led to me transitioning career paths from medicine into research. Following my M.S. degree, I decided to enter into the Program of Immunology and Infectious Diseases at Washington State University as a PhD student. After completion of my laboratory rotations, I decided to join the laboratory of Dr. Ilia Karatsoreos in the Program of Integrative Physiology and Neuroscience. In January 2020, I moved with the Karatsoreos lab to the University of Massachusetts Amherst, where I am now a PhD student in the Program of Neuroscience and Behavior.

